name: geojson
description: Utilities to work with geojson data. Parser with a reactive api,
  search and geofencing
homepage: https://github.com/lucygeneric/geojson
version: 0.10.4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  extra_pedantic: ^1.5.0
  geodesy: ^0.4.0-nullsafety.0
  geopoint2: ^0.9.0
  iso: ^1.0.0
  meta: ^1.3.0
  pedantic: ^1.11.0

dev_dependencies:
  test: ^1.17.5
